### ISSUE TITLE
How to test the pre-trained models on Google Colab?

### ISSUE THREAD

**Issue by nooreldeenmansour** [kregmi/cross-view-synthesis#36]
Hi,

I've been trying to test/reproduce the model on Google Colab, but not sure what am I doing wrong, the link of the notebook with the steps I've taken can be found [here](https://colab.research.google.com/drive/1X7OX8lG5kBZHF61kt6OgyYspIAN7VSuv?usp=sharing).
The summary of the steps is:
- I've installed the dependencies.
- downloaded the models and copied them to `checkpoints` directory inside the repository.
![image](https://user-images.githubusercontent.com/61914159/133595294-9291e980-8d91-4a61-b109-9c543d0c5509.png)
- Tried to test the model with the commands in README.md on the **sample data**.
```
DATA_ROOT=./datasets/AB_AsBs name=sample_images which_direction=a2g phase=sample which_epoch=35 th test_fork.lua 
```

The output error can be found in the last cell in the notebook but here is a screenshot
![image](https://user-images.githubusercontent.com/61914159/133594639-ea131528-e9d7-4faf-922d-dde6c00b5e4d.png)
___

Any help would be appreciated, thanks.

**Comment by kregmi** [comment]
Hope you have already resolved the issue by now. Looking at the error it seems to me that the path to the data/images is incorrect.
