### ISSUE TITLE
About the computation of PSNR

### ISSUE THREAD

**Issue by XiaLiPKU** [kregmi/cross-view-synthesis#38]
Dear author,

Thanks for your contribution!
I'm wondering why there should be 128 instead of 255.
The value of the image should be in range [0, 1] or [0, 255], instead of [-1, 1]

https://github.com/kregmi/cross-view-image-synthesis/blob/402ce4c26d4584ef35ee25be306bc2ad0e018736/Evaluation/my_image_error_measures.lua#L39

**Comment by kregmi** [comment]
That's correct. It was an error.
